"""Add leave_type and change date to datetime

Revision ID: 476ecb5dd4d9
Revises: 5ce296c46002
Create Date: 2026-02-24 13:41:57.801114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '476ecb5dd4d9'
down_revision = '5ce296c46002'
branch_labels = None
depends_on = None


def upgrade():
    # 1️⃣ leave_type 컬럼 추가
    op.add_column('leave', sa.Column('leave_type', sa.String(length=20), nullable=True))

    # 2️⃣ 임시 datetime 컬럼 추가
    op.add_column('leave', sa.Column('start_date_tmp', sa.DateTime(), nullable=True))
    op.add_column('leave', sa.Column('end_date_tmp', sa.DateTime(), nullable=True))

    # 3️⃣ 기존 DATE → DATETIME 변환 (시간 00:00:00 붙임)
    conn = op.get_bind()
    conn.execute(text("""
        UPDATE leave
        SET start_date_tmp = start_date || ' 00:00:00',
            end_date_tmp = end_date || ' 23:59:59'
    """))

    # 4️⃣ 기존 컬럼 제거
    op.drop_column('leave', 'start_date')
    op.drop_column('leave', 'end_date')

    # 5️⃣ 임시 컬럼을 원래 이름으로 변경
    op.alter_column('leave', 'start_date_tmp', new_column_name='start_date')
    op.alter_column('leave', 'end_date_tmp', new_column_name='end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('leave_type')

    # ### end Alembic commands ###
