"""Add attendance table

Revision ID: 542bf2f2d480
Revises: 476ecb5dd4d9
Create Date: 2026-03-19 14:39:34.585092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542bf2f2d480'
down_revision = '476ecb5dd4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_column('leave_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
