"""add pending_days to leave_balance

Revision ID: 5729d600b0d7
Revises: 
Create Date: 2026-01-16 17:21:31.106593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5729d600b0d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balance', schema=None) as batch_op:
        batch_op.drop_column('pending_days')

    # ### end Alembic commands ###
